name: CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and Deploy Locally
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          cat > .env << EOF
          BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL=${{ secrets.BETTER_AUTH_URL }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          GO_API_URL=${{ secrets.GO_API_URL }}
          EOF
      - name: Create .env file
        run: |
          cat > .env.local << EOF
          BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL=${{ secrets.BETTER_AUTH_URL }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          GO_API_URL=${{ secrets.GO_API_URL }}
          EOF
      - name: Deploy with Docker Compose
        run: |
          docker compose down || true
          docker compose up -d --build
